#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Long;

my %opt;
GetOptions(\%opt, 'begin=i', 'end=i', 'archive', 'recent');
die if not defined $opt{begin} or not defined $opt{end};

generate_archive_tables() if ($opt{archive});
generate_recent_tables() if ($opt{recent});

sub generate_recent_tables
{
	for my $i ($opt{begin} .. $opt{end}) {
		print <<SQL;
CREATE TABLE posts.recent_$i (
	CHECK (board = $i)
) INHERITS (posts.recent);
CREATE INDEX ON posts.recent_$i (id);
CREATE INDEX ON posts.recent_$i (board);
SQL
	}
}

sub generate_archive_tables
{
	for my $i ($opt{begin} .. $opt{end}) {
		print <<SQL;
CREATE TABLE posts.archive_$i (
	CHECK (board = $i)
) INHERITS (posts.archives);
CREATE INDEX ON posts.archive_$i (id);
CREATE INDEX ON posts.archive_$i (board);
SQL
	}
}
