BEGIN;

DROP TABLE IF EXISTS sessions;

CREATE TABLE sessions (
	id BIGSERIAL,
	session_key TEXT,
	active BOOLEAN DEFAULT TRUE,
	user_id INTEGER REFERENCES users,
	pid INTEGER DEFAULT 0,
	visible BOOLEAN DEFAULT TRUE,
	ip_addr TEXT,
);

COMMIT;
