#!/usr/bin/env perl

use strict;
use warnings;

main();

sub main {
	my ($dir, $input, $output) = @ARGV;

	open my $fin, '<', "$dir/$input" or die $!;
	open my $fout, '>', $output or die $!;

	while (<$fin>) {
		chomp;
		if (/(template|partial) +(.+)>/) {
			my $prefix = substr $1, 0, 1;
			print $fout "<script type='text/html' id='$prefix-$2'>";
			include_file($dir, $fout, $2, $prefix);
			print $fout "</script>";
		} else {
			s/^\s+//;
			print $fout $_;
		}
	}

	close $fin;
	close $fout;
}

sub include_file {
	my ($dir, $fout, $tmpl, $prefix) = @_;
	open my $fh, '<', "$dir/tmpl/$tmpl.htm" . ($prefix eq 't' ? 'l' : '') or die $!;
	while (<$fh>) {
		chomp;
		s/^\s+//;
		print $fout $_;
	}
	close $fh;
}

1;
