#!/usr/bin/env perl

use strict;
use warnings;

main();

sub main {
	my ($dir, $input, $output) = @ARGV;

	open my $fin, '<', "$dir/$input" or die $!;
	open my $fout, '>', $output or die $!;

	while (<$fin>) {
		chomp;
		if (/template +(.+)>/) {
			print $fout "<script type='text/html' id='t-$1'>";
			include_file($dir, $fout, $1);
			print $fout "</script>";
		} else {
			s/^\s+//;
			print $fout $_;
		}
	}

	close $fin;
	close $fout;
}

sub include_file {
	my ($dir, $fout, $tmpl) = @_;
	open my $fh, '<', "$dir/tmpl/$tmpl.htm" or die $!;
	while (<$fh>) {
		chomp;
		s/^\s+//;
		print $fout $_;
	}
	close $fh;
}

1;
